commerce_payment.commerce_payment_gateway.plugin.paymentdrupal_v9:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    partner_name:
      type: string
      label: 'Partner Name'
    secret_key:
      type: string
      label: 'Secret Key'
    redirect_url:
      type: string
      label: 'Redirect Url'
    test_url:
      type: string
      label: 'Test Url'

